name: pomotimer_time_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  circular_countdown_timer: 0.2.0
  awesome_notifications: ^0.6.21
  timezone: 0.8.0
  get_storage: 2.0.3
  flutter_icons: 1.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: 0.9.2

flutter_icons: 
  ios: true
  android: true
  image_path: "assets/logo.png"

flutter: 
  uses-material-design: true

